# Métodos Númericos
## Isaac González
### Tarea 10

---

In [4]:
# ----------------------------- logging --------------------------
import logging
import numpy as np
from sys import stdout
from datetime import datetime


logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

[01-27 22:19:48][INFO] 2026-01-27 22:19:48.370122


1. Realice las siguientes multiplicaciones matriz-matriz

In [17]:
import numpy as np
def multiplicar_matrices(A, B):
    ''''
    Multiplica dos matrices A(m x n) y B(n x p) usando listas anidadas,
    retorna la matriz resultante (m x p)
    '''
    if not A or not B or not A[0] or not B[0]:
        raise ValueError("Las matrices no pueden estar vacías,")
    
    m, n = len(A), len(A[0])
    n2, p = len(B), len(B[0])
    
    #Verificar dimensiones compatibles
    if n != n2:
        raise ValueError(f"Dimensiones incompatibles: A es {m}x{n} y B es {n2}x{p}")

    #Multiplicación
    
    R = [[0 for _ in range(p)] for _ in range(m)]
    for i in range(m):
        for k in range(n):
            aik = A[i][k]
            for j in range(p):
                R[i][j] += aik * B[k][j]
    return np.array(R)


a.  

A = 
\begin{bmatrix}
2 & -3\\
3 & -1
\end{bmatrix} \\

B = 
\begin{bmatrix}
1 & 5\\
2 & 0
\end{bmatrix}




In [18]:
A = [
    [2,-3],
    [3,-1]
]

B = [
    [1,5],
    [2,0]
]

print(multiplicar_matrices(A,B))

[[-4 10]
 [ 1 15]]


Comprobación

In [8]:
import numpy as np

R = np.matmul(A,B)
print(R)


[[-4 10]
 [ 1 15]]


A = 

\begin{bmatrix}
2 & -3\\
3 & -1
\end{bmatrix}

B =

\begin{bmatrix}
1 & 5 & -4\\
-3 & 2 & 0
\end{bmatrix}


In [19]:
A = [
    [2,-3],
    [3,-1]
]

B = [
    [1, 5, -4],
    [-3, 2, 0]
]

print(multiplicar_matrices(A, B))

[[ 11   4  -8]
 [  6  13 -12]]


Comprobación

In [10]:
import numpy as np

R = np.matmul(A, B)
print(R)

[[ 11   4  -8]
 [  6  13 -12]]


c.

A =

\begin{bmatrix}
2 & -3 & 1\\
4 & 3 & 0\\
5 & 2 & -4
\end{bmatrix}

B=

\begin{bmatrix}
0 & 1 & -2\\
1 & 0 & -1\\
2 & 3 & -2
\end{bmatrix}

In [20]:
A = [
    [2,-3,1],
    [4,3,0],
    [5,2,-4]
]

B = [
    [0,1,-2],
    [1,0,-1],
    [2,3,-2]
]

print(multiplicar_matrices(A,B))

[[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]


Comprobación

In [14]:
import numpy as np

R = np.matmul(A,B)
print(R)

[[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]


d.  

A = 

\begin{bmatrix}
2 & 1 & 2\\
-2 & 3 & 0\\
2 & -1 & 3
\end{bmatrix}

B =

\begin{bmatrix}
1 & -2\\
-4 & 1\\
0 & 2
\end{bmatrix}

In [21]:
A = [
    [2,1,2],
    [-2,3,0],
    [2,-1,3]
]

B = [
    [1,-2],
    [-4,1],
    [0,2]
]

print(multiplicar_matrices(A,B))

[[ -2   1]
 [-14   7]
 [  6   1]]


comprobación

In [16]:
import numpy as np

R = np.matmul(A,B)
print(R)

[[ -2   1]
 [-14   7]
 [  6   1]]


2. Determine cuáles de las siguientes matrices son no singulares y calcule la inversa de esas matrices:

In [5]:
# ####################################################################
def gauss_jordan(A: np.ndarray) -> np.ndarray:
    """Realiza la eliminación de Gauss-Jordan

    ## Parameters

    ``A``: matriz del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(k), donde n es el número de incógnitas.

    ## Return

    ``A``: matriz reducida por filas.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)
    n = A.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        # for j in range(i + 1, n): # Eliminación gaussiana
        for j in range(n):  # Gauss-Jordan
            if j == i:
                continue  # skip pivot row

            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

            # dividir para la diagonal
        A[i, :] = A[i, :] / A[i, i]

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

  

    return A

In [6]:
def matriz_inversa(A: np.ndarray) -> np.ndarray:
    """Calcula la matriz inversa de A usando eliminación de Gauss-Jordan

    ## Parameters

    ``A``: matriz cuadrada a invertir.

    ## Return

    ``A_inv``: matriz inversa de A.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)

    n = A.shape[0]
   
    A_aumentada = np.hstack((A, np.eye(n)))

    A_reducida = gauss_jordan(A_aumentada)

    A_inversa = A_reducida[:, n:]

    return A_inversa 

In [7]:

def es_no_singular_numpy(A):
    return np.linalg.det(A) != 0

a.
 

\begin{bmatrix}
4 & 2 & 6 \\
3 & 0 & 7 \\
-2 & -1 & -3
\end{bmatrix}



In [ ]:

a = np.array([[4, 2, 6],
              [3, 0, 7],
              [-2, -1, -3]])

es_no_singular_numpy(a)

np.False_

b.

\begin{bmatrix}
1 & 2 & 0 \\
2 & 1 & -1 \\
3 & 1 & 1
\end{bmatrix}

In [10]:

b = np.array([[1, 2, 0],
              [2, 1, -1],
              [3, 1, 1]])

es_no_singular_numpy(b)


np.True_

In [11]:

matriz_inversa(b)

[01-27 23:36:22][INFO] 
[[ 1.  2.  0.  1.  0.  0.]
 [ 0. -3. -1. -2.  1.  0.]
 [ 0. -5.  1. -3.  0.  1.]]
[01-27 23:36:22][INFO] 
[[ 1.          0.         -0.66666667 -0.33333333  0.66666667  0.        ]
 [-0.          1.          0.33333333  0.66666667 -0.33333333 -0.        ]
 [ 0.          0.          2.66666667  0.33333333 -1.66666667  1.        ]]
[01-27 23:36:22][INFO] 
[[ 1.     0.     0.    -0.25   0.25   0.25 ]
 [-0.     1.     0.     0.625 -0.125 -0.125]
 [ 0.     0.     1.     0.125 -0.625  0.375]]


array([[-0.25 ,  0.25 ,  0.25 ],
       [ 0.625, -0.125, -0.125],
       [ 0.125, -0.625,  0.375]])

c.

