# Métodos Númericos
## Isaac González
### Tarea 10

---

In [2]:
# ----------------------------- logging --------------------------
import logging
import numpy as np
from sys import stdout
from datetime import datetime


logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

[01-27 23:38:13][INFO] 2026-01-27 23:38:13.603297


1. Realice las siguientes multiplicaciones matriz-matriz

In [17]:
import numpy as np
def multiplicar_matrices(A, B):
    ''''
    Multiplica dos matrices A(m x n) y B(n x p) usando listas anidadas,
    retorna la matriz resultante (m x p)
    '''
    if not A or not B or not A[0] or not B[0]:
        raise ValueError("Las matrices no pueden estar vacías,")
    
    m, n = len(A), len(A[0])
    n2, p = len(B), len(B[0])
    
    #Verificar dimensiones compatibles
    if n != n2:
        raise ValueError(f"Dimensiones incompatibles: A es {m}x{n} y B es {n2}x{p}")

    #Multiplicación
    
    R = [[0 for _ in range(p)] for _ in range(m)]
    for i in range(m):
        for k in range(n):
            aik = A[i][k]
            for j in range(p):
                R[i][j] += aik * B[k][j]
    return np.array(R)


a.  

A = 
\begin{bmatrix}
2 & -3\\
3 & -1
\end{bmatrix} \\

B = 
\begin{bmatrix}
1 & 5\\
2 & 0
\end{bmatrix}




In [18]:
A = [
    [2,-3],
    [3,-1]
]

B = [
    [1,5],
    [2,0]
]

print(multiplicar_matrices(A,B))

[[-4 10]
 [ 1 15]]


Comprobación

In [8]:
import numpy as np

R = np.matmul(A,B)
print(R)


[[-4 10]
 [ 1 15]]


A = 

\begin{bmatrix}
2 & -3\\
3 & -1
\end{bmatrix}

B =

\begin{bmatrix}
1 & 5 & -4\\
-3 & 2 & 0
\end{bmatrix}


In [19]:
A = [
    [2,-3],
    [3,-1]
]

B = [
    [1, 5, -4],
    [-3, 2, 0]
]

print(multiplicar_matrices(A, B))

[[ 11   4  -8]
 [  6  13 -12]]


Comprobación

In [10]:
import numpy as np

R = np.matmul(A, B)
print(R)

[[ 11   4  -8]
 [  6  13 -12]]


c.

A =

\begin{bmatrix}
2 & -3 & 1\\
4 & 3 & 0\\
5 & 2 & -4
\end{bmatrix}

B=

\begin{bmatrix}
0 & 1 & -2\\
1 & 0 & -1\\
2 & 3 & -2
\end{bmatrix}

In [20]:
A = [
    [2,-3,1],
    [4,3,0],
    [5,2,-4]
]

B = [
    [0,1,-2],
    [1,0,-1],
    [2,3,-2]
]

print(multiplicar_matrices(A,B))

[[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]


Comprobación

In [14]:
import numpy as np

R = np.matmul(A,B)
print(R)

[[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]


d.  

A = 

\begin{bmatrix}
2 & 1 & 2\\
-2 & 3 & 0\\
2 & -1 & 3
\end{bmatrix}

B =

\begin{bmatrix}
1 & -2\\
-4 & 1\\
0 & 2
\end{bmatrix}

In [21]:
A = [
    [2,1,2],
    [-2,3,0],
    [2,-1,3]
]

B = [
    [1,-2],
    [-4,1],
    [0,2]
]

print(multiplicar_matrices(A,B))

[[ -2   1]
 [-14   7]
 [  6   1]]


comprobación

In [16]:
import numpy as np

R = np.matmul(A,B)
print(R)

[[ -2   1]
 [-14   7]
 [  6   1]]


2. Determine cuáles de las siguientes matrices son no singulares y calcule la inversa de esas matrices:

In [5]:
# ####################################################################
def gauss_jordan(A: np.ndarray) -> np.ndarray:
    """Realiza la eliminación de Gauss-Jordan

    ## Parameters

    ``A``: matriz del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(k), donde n es el número de incógnitas.

    ## Return

    ``A``: matriz reducida por filas.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)
    n = A.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        # for j in range(i + 1, n): # Eliminación gaussiana
        for j in range(n):  # Gauss-Jordan
            if j == i:
                continue  # skip pivot row

            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

            # dividir para la diagonal
        A[i, :] = A[i, :] / A[i, i]

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

  

    return A

In [4]:
def matriz_inversa(A: np.ndarray) -> np.ndarray:
    """Calcula la matriz inversa de A usando eliminación de Gauss-Jordan

    ## Parameters

    ``A``: matriz cuadrada a invertir.

    ## Return

    ``A_inv``: matriz inversa de A.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)

    n = A.shape[0]
   
    A_aumentada = np.hstack((A, np.eye(n)))

    A_reducida = gauss_jordan(A_aumentada)

    A_inversa = A_reducida[:, n:]

    return A_inversa 

In [7]:

def es_no_singular_numpy(A):
    return np.linalg.det(A) != 0

a.
 

\begin{bmatrix}
4 & 2 & 6 \\
3 & 0 & 7 \\
-2 & -1 & -3
\end{bmatrix}



In [ ]:

a = np.array([[4, 2, 6],
              [3, 0, 7],
              [-2, -1, -3]])

es_no_singular_numpy(a)

np.False_

b.

\begin{bmatrix}
1 & 2 & 0 \\
2 & 1 & -1 \\
3 & 1 & 1
\end{bmatrix}

In [10]:

b = np.array([[1, 2, 0],
              [2, 1, -1],
              [3, 1, 1]])

es_no_singular_numpy(b)


np.True_

In [11]:

matriz_inversa(b)

[01-27 23:36:22][INFO] 
[[ 1.  2.  0.  1.  0.  0.]
 [ 0. -3. -1. -2.  1.  0.]
 [ 0. -5.  1. -3.  0.  1.]]
[01-27 23:36:22][INFO] 
[[ 1.          0.         -0.66666667 -0.33333333  0.66666667  0.        ]
 [-0.          1.          0.33333333  0.66666667 -0.33333333 -0.        ]
 [ 0.          0.          2.66666667  0.33333333 -1.66666667  1.        ]]
[01-27 23:36:22][INFO] 
[[ 1.     0.     0.    -0.25   0.25   0.25 ]
 [-0.     1.     0.     0.625 -0.125 -0.125]
 [ 0.     0.     1.     0.125 -0.625  0.375]]


array([[-0.25 ,  0.25 ,  0.25 ],
       [ 0.625, -0.125, -0.125],
       [ 0.125, -0.625,  0.375]])

c.

\begin{bmatrix}
1 & 1 & -1 & 1 \\
1 & 2 & -4 & -2 \\
2 & 1 & 1 & 5 \\
-1 & 0 & -2 & -4
\end{bmatrix}


In [8]:
c= np.array([[1, 1, -1, 1],
                [1, 2, -4, -2],
                [2, 1, 1, 5],
                [-1, 0, -2, -4]])


es_no_singular_numpy(c)

np.False_

d.

\begin{bmatrix}
4 & 0 & 0 & 0 \\
6 & 7 & 0 & 0 \\
9 & 11 & 1 & 0 \\
5 & 4 & 1 & 1
\end{bmatrix}

In [9]:
d = np.array([[4, 0, 0, 0],
                [6, 7, 0, 0],
                [9, 11, 1, 0],
                [5, 4, 1, 1]])

es_no_singular_numpy(d)

np.True_

In [10]:
matriz_inversa(d)


[01-27 23:40:31][INFO] 
[[ 1.    0.    0.    0.    0.25  0.    0.    0.  ]
 [ 0.    7.    0.    0.   -1.5   1.    0.    0.  ]
 [ 0.   11.    1.    0.   -2.25  0.    1.    0.  ]
 [ 0.    4.    1.    1.   -1.25  0.    0.    1.  ]]
[01-27 23:40:31][INFO] 
[[ 1.      0.      0.      0.      0.25    0.      0.      0.    ]
 [ 0.      1.      0.25    0.25   -0.3125  0.      0.      0.25  ]
 [ 0.      0.     -1.75   -2.75    1.1875  0.      1.     -2.75  ]
 [ 0.      0.     -1.75   -1.75    0.6875  1.      0.     -1.75  ]]
[01-27 23:40:31][INFO] 
[[ 1.          0.          0.          0.          0.25        0.
   0.          0.        ]
 [ 0.          1.          0.         -0.14285714 -0.14285714  0.
   0.14285714 -0.14285714]
 [-0.         -0.          1.          1.57142857 -0.67857143 -0.
  -0.57142857  1.57142857]
 [ 0.          0.          0.          1.         -0.5         1.
  -1.          1.        ]]
[01-27 23:40:31][INFO] 
[[ 1.          0.          0.          0.          0.25  

array([[ 0.25      ,  0.        ,  0.        ,  0.        ],
       [-0.21428571,  0.14285714,  0.        ,  0.        ],
       [ 0.10714286, -1.57142857,  1.        ,  0.        ],
       [-0.5       ,  1.        , -1.        ,  1.        ]])

3. Resuelva los sistemas lineales 4 x 4 que tienen la misma matriz de coeficientes

In [1]:

from src import descomposicion_LU, resolver_LU

[01-27 23:46:22][INFO] 2026-01-27 23:46:22.980513


1.

\begin{cases}
x_1 - x_2 + 2x_3 - x_4 = 6 \\
x_1 - x_3 + x_4 = 4 \\
2x_1 + x_2 + 3x_3 - 4x_4 = -2 \\
- x_2 + x_3 - x_4 = 5
\end{cases}

In [4]:
import numpy as np
A = np.array([[1, -1, 2, -1],
                [1, 0, -1, 1],
                [2, 1, 3, -4],
                [0, -1, 1, -1]])

L1, U1 = descomposicion_LU(np.array(A))
b = np.array([6,4,-2,5])
x_1 = resolver_LU(L1, U1, b)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)   
print("Solución del sistema")
print(x_1)

[01-27 23:50:36][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  3. -1. -2.]
 [ 0. -1.  1. -1.]]
[01-27 23:50:36][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0. -2.  1.]]
[01-27 23:50:36][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]
[01-27 23:50:36][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]
[01-27 23:50:36][INFO] Sustitución hacia adelante
[01-27 23:50:36][INFO] y = 
[[ 6.]
 [-2.]
 [-8.]
 [ 1.]]
[01-27 23:50:36][INFO] Sustitución hacia atrás
[01-27 23:50:36][INFO] i = 2
[01-27 23:50:36][INFO] suma = [8.]
[01-27 23:50:36][INFO] U[i, i] = 8.0
[01-27 23:50:36][INFO] y[i] = [-8.]
[01-27 23:50:36][INFO] i = 1
[01-27 23:50:36][INFO] suma = [4.]
[01-27 23:50:36][INFO] U[i, i] = 1.0
[01-27 23:50:36][INFO] y[i] = [-2.]
[01-27 23:50:36][INFO] i = 0
[01-27 23:50:36][INFO] suma = [3.]
[01-27 23:50:36][INFO] U[i, i] = 1.0
[01-27 23:50:36][INFO] y[i] = [6.]
Matriz L:
[[ 1.    0.    0.    0

\begin{cases}
x_1 - x_2 + 2x_3 - x_4 = 1 \\
x_1 - x_3 + x_4 = 1 \\
2x_1 + x_2 + 3x_3 - 4x_4 = 2 \\
- x_2 + x_3 - x_4 = -1
\end{cases}

In [5]:
L1, U1 = descomposicion_LU(np.array(A))
b2 = np.array([1,1,2,-1])
x_2 = resolver_LU(L1, U1, b2)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)   
print("Solución del sistema")
print(x_2)

[01-27 23:52:22][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  3. -1. -2.]
 [ 0. -1.  1. -1.]]
[01-27 23:52:22][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0. -2.  1.]]
[01-27 23:52:22][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]
[01-27 23:52:22][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]
[01-27 23:52:22][INFO] Sustitución hacia adelante
[01-27 23:52:22][INFO] y = 
[[ 1.]
 [ 0.]
 [ 0.]
 [-1.]]
[01-27 23:52:22][INFO] Sustitución hacia atrás
[01-27 23:52:22][INFO] i = 2
[01-27 23:52:22][INFO] suma = [-8.]
[01-27 23:52:22][INFO] U[i, i] = 8.0
[01-27 23:52:22][INFO] y[i] = [0.]
[01-27 23:52:22][INFO] i = 1
[01-27 23:52:22][INFO] suma = [-1.]
[01-27 23:52:22][INFO] U[i, i] = 1.0
[01-27 23:52:22][INFO] y[i] = [0.]
[01-27 23:52:22][INFO] i = 0
[01-27 23:52:22][INFO] suma = [0.]
[01-27 23:52:22][INFO] U[i, i] = 1.0
[01-27 23:52:22][INFO] y[i] = [1.]
Matriz L:
[[ 1.    0.    0.    0

4. Encuentre los valores de A que hacen que la siguiente matriz sea singular.

A =
\begin{bmatrix}
1 & -1 & \alpha \\
2 & 2 & 1 \\
0 & \alpha & -\frac{3}{2}
\end{bmatrix}

In [6]:
import sympy as sp

a = sp.symbols('a')

M = sp.Matrix([
    [1, -1, a],
    [2,  2, 1],
    [0,  a, -sp.Rational(3, 2)]
])

detM = M.det()

print("Determinante de la matriz:")
sp.pprint(detM)

sol = sp.solve(detM, a)

print("\nValores de a que hacen singular la matriz:")
print(sol)


Determinante de la matriz:
   2        
2⋅a  - a - 6

Valores de a que hacen singular la matriz:
[-3/2, 2]


5. Resuelva los siguientes sistemas lineales:

a.

In [7]:
A= np.array([[1, 0, 0],
                [2, 1, 0],
                [-1, 0, 1]])

B = np.array([[2, 3, -1],
                [0, -2, 1],
                [0, 0, 3]])

C = A @ B

L1, U1 = descomposicion_LU(np.array(C))
b = np.array([2,-1,1])
x_1 = resolver_LU(L1, U1, b)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)   
print("Solución del sistema:")
print(x_1)

[01-27 23:58:49][INFO] 
[[ 2.  3. -1.]
 [ 0. -2.  1.]
 [ 0.  0.  3.]]
[01-27 23:58:49][INFO] 
[[ 2.  3. -1.]
 [ 0. -2.  1.]
 [ 0.  0.  3.]]
[01-27 23:58:49][INFO] 
[[ 2.  3. -1.]
 [ 0. -2.  1.]
 [ 0.  0.  3.]]
[01-27 23:58:49][INFO] Sustitución hacia adelante
[01-27 23:58:49][INFO] y = 
[[ 2.]
 [-5.]
 [ 3.]]
[01-27 23:58:49][INFO] Sustitución hacia atrás
[01-27 23:58:49][INFO] i = 1
[01-27 23:58:49][INFO] suma = [1.]
[01-27 23:58:49][INFO] U[i, i] = -2.0
[01-27 23:58:49][INFO] y[i] = [-5.]
[01-27 23:58:49][INFO] i = 0
[01-27 23:58:49][INFO] suma = [8.]
[01-27 23:58:49][INFO] U[i, i] = 2.0
[01-27 23:58:49][INFO] y[i] = [2.]
Matriz L:
[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1. -0.  1.]]
Matriz U:
[[ 2.  3. -1.]
 [ 0. -2.  1.]
 [ 0.  0.  3.]]
Solución del sistema:
[[-3.]
 [ 3.]
 [ 1.]]


b.

In [8]:
A= np.array([[2, 0, 0],
                [-1, 1, 0],
                [3, 2, -1]])

B = np.array([[1, 1, 1],
                [0, 1, 2],
                [0, 0, 1]])

C = A @ B

L1, U1 = descomposicion_LU(np.array(C))
b2 = np.array([-1,3,0])
x_2 = resolver_LU(L1, U1, b2)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)   
print("Solución del sistema:")
print(x_2)

[01-27 23:59:34][INFO] 
[[2. 2. 2.]
 [0. 1. 2.]
 [0. 2. 3.]]
[01-27 23:59:34][INFO] 
[[ 2.  2.  2.]
 [ 0.  1.  2.]
 [ 0.  0. -1.]]
[01-27 23:59:34][INFO] 
[[ 2.  2.  2.]
 [ 0.  1.  2.]
 [ 0.  0. -1.]]
[01-27 23:59:34][INFO] Sustitución hacia adelante
[01-27 23:59:34][INFO] y = 
[[-1. ]
 [ 2.5]
 [-3.5]]
[01-27 23:59:34][INFO] Sustitución hacia atrás
[01-27 23:59:34][INFO] i = 1
[01-27 23:59:34][INFO] suma = [7.]
[01-27 23:59:34][INFO] U[i, i] = 1.0
[01-27 23:59:34][INFO] y[i] = [2.5]
[01-27 23:59:34][INFO] i = 0
[01-27 23:59:34][INFO] suma = [-2.]
[01-27 23:59:34][INFO] U[i, i] = 2.0
[01-27 23:59:34][INFO] y[i] = [-1.]
Matriz L:
[[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [ 1.5  2.   1. ]]
Matriz U:
[[ 2.  2.  2.]
 [ 0.  1.  2.]
 [ 0.  0. -1.]]
Solución del sistema:
[[ 0.5]
 [-4.5]
 [ 3.5]]


6. Factorice las siguientes matrices en la descomposición $LU$ mediante el algoritmo de factorización LU
con $l_{ii} = 1 $ para todas las $i$.

a. 

\begin{bmatrix}
2 & -1 & 1 \\
3 & 3 & 9 \\
3 & 3 & 5
\end{bmatrix}

In [9]:
A = np.array([[2, -1, 1],
              [3, 3, 9],
                [3, 3, 5]])

L,U = descomposicion_LU(A)
print("Matriz L:")
print(L)
print("Matriz U:")
print(U)  

[01-28 00:02:05][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   4.5  3.5]]
[01-28 00:02:05][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
[01-28 00:02:05][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
Matriz L:
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]
Matriz U:
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]


b.

\begin{bmatrix}
1.012 & -2.132 & 3.104 \\
-2.132 & 4.096 & -7.013 \\
3.104 & -7.013 & 0.014
\end{bmatrix}

In [10]:

B = np.array([[1.012, -2.132, 3.104],
              [-2.132, 4.096, -7.013],
                [3.104, -7.013, 0.014]])


L,U = descomposicion_LU(B)
print("Matriz L:")
print(L)
print("Matriz U:")
print(U)   

[01-28 00:02:48][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.         -0.47374308 -9.50656917]]
[01-28 00:02:48][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
[01-28 00:02:48][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
Matriz L:
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  1.19775553  1.        ]]
Matriz U:
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]


c.

\begin{bmatrix}
2 & 0 & 0 & 0 \\
1 & 1.5 & 0 & 0 \\
0 & -3 & 0.5 & 0 \\
2 & -2 & 1 & 1
\end{bmatrix}

In [11]:
C = np.array([[2, 0, 0, 0],
                [1, 1.5, 0, 0],
                    [0, -3, 0.5, 0],
                    [2, -2, 1, 1]])

L,U = descomposicion_LU(C)
print("Matriz L:")
print(L)
print("Matriz U:")
print(U)   

[01-28 00:03:25][INFO] 
[[ 2.   0.   0.   0. ]
 [ 0.   1.5  0.   0. ]
 [ 0.  -3.   0.5  0. ]
 [ 0.  -2.   1.   1. ]]
[01-28 00:03:25][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  1.  1. ]]
[01-28 00:03:25][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]
[01-28 00:03:25][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]
Matriz L:
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.         -2.          1.          0.        ]
 [ 1.         -1.33333333  2.          1.        ]]
Matriz U:
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]


d.

\begin{bmatrix}
2.1756 & 4.0231 & -2.1732 & 5.1967 \\
-4.0231 & 6.0000 & 0 & 1.1973 \\
-1.0000 & -5.2107 & 1.1111 & 0 \\
6.0235 & 7.0000 & 0 & -4.1561
\end{bmatrix}

In [ ]:
D = np.array([[2.1756, 4.0231, -2.1732, 5.1967],
              [-4.0231, 6.0000, 0, 1.973],
              [-1.0000, -5.2107, 1.1111, 0],
              [6.0235, 7.0000, 0, -4.1561]])

L,U = descomposicion_LU(D)
print("Matriz L:")
print(L)
print("Matriz U:")
print(U) 

7. Modifique el algoritmo de eliminación gaussiana de tal forma que se pueda utilizar para resolver un sistema lineal usando la descomposición LU y, a continuación, resuelva los siguientes sistemas lineales.

\begin{cases}
2x_1 - x_2 + x_3 = -1 \\
3x_1 + 3x_2 + 9x_3 = 0 \\
3x_1 + 3x_2 + 5x_3 = 4
\end{cases}

In [12]:
A = np.array([[2,-1,1],
              [3,3,9],
                [3,3,5]])

L1, U1 = descomposicion_LU(np.array(A))
b = np.array([1,0,4])
x_1 = resolver_LU(L1, U1, b)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)   
print("Solución del sistema:")
print(x_1)

[01-28 00:06:31][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   4.5  3.5]]
[01-28 00:06:31][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
[01-28 00:06:31][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
[01-28 00:06:31][INFO] Sustitución hacia adelante
[01-28 00:06:31][INFO] y = 
[[ 1. ]
 [-1.5]
 [ 4. ]]
[01-28 00:06:31][INFO] Sustitución hacia atrás
[01-28 00:06:31][INFO] i = 1
[01-28 00:06:31][INFO] suma = [-7.5]
[01-28 00:06:31][INFO] U[i, i] = 4.5
[01-28 00:06:31][INFO] y[i] = [-1.5]
[01-28 00:06:31][INFO] i = 0
[01-28 00:06:31][INFO] suma = [-2.33333333]
[01-28 00:06:31][INFO] U[i, i] = 2.0
[01-28 00:06:31][INFO] y[i] = [1.]
Matriz L:
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]
Matriz U:
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
Solución del sistema:
[[ 1.66666667]
 [ 1.33333333]
 [-1.        ]]


\begin{cases}
1.012x_1 - 2.132x_2 + 3.104x_3 = 1.984 \\
-2.132x_1 + 4.096x_2 - 7.013x_3 = -5.049 \\
3.104x_1 - 7.013x_2 + 0.014x_3 = -3.895
\end{cases}

In [13]:
B = np.array([[1.012, -2.132, 3.104],
              [-2.132, 4.096, -7.013],
                [3.104, -7.013, 0.014]])


L1, U1 = descomposicion_LU(np.array(B))
b2 = np.array([1.984, -5.049, -3.895])
x_2 = resolver_LU(L1, U1, b2)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)   
print("Solución del sistema Ax=b:")
print(x_2)

[01-28 00:07:27][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.         -0.47374308 -9.50656917]]
[01-28 00:07:27][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
[01-28 00:07:27][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
[01-28 00:07:27][INFO] Sustitución hacia adelante
[01-28 00:07:27][INFO] y = 
[[ 1.984     ]
 [-0.86926877]
 [-8.93914077]]
[01-28 00:07:27][INFO] Sustitución hacia atrás
[01-28 00:07:27][INFO] i = 1
[01-28 00:07:27][INFO] suma = [-0.47374308]
[01-28 00:07:27][INFO] U[i, i] = -0.3955256916996053
[01-28 00:07:27][INFO] y[i] = [-0.86926877]
[01-28 00:07:27][INFO] i = 0
[01-28 00:07:27][INFO] suma = [0.972]
[01-28 00:07:27][INFO] U[i, i] = 1.012
[01-28 00:07:27][INFO] y[i] = [1.984]
Matriz L:
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 

\begin{cases}
2x_1 = 3 \\
x_1 + 1.5x_2 = 4.5 \\
-3x_2 + 0.5x_3 = -6.6 \\
2x_1 - 2x_2 + x_3 + x_4 = 0.8
\end{cases}

In [14]:
C = np.array ([[2, 0, 0, 0],
               [1, 1.5, 0, 0],
               [0, -3, 0.5, 0],
                [2, -2, 1, 1]])

L1, U1 = descomposicion_LU(np.array(C))
b3 = np.array([3, 4.5, -6.6, 0.8])
x_3 = resolver_LU(L1, U1, b3)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)   
print("Solución del sistema Ax=b:")
print(x_3)

[01-28 00:08:18][INFO] 
[[ 2.   0.   0.   0. ]
 [ 0.   1.5  0.   0. ]
 [ 0.  -3.   0.5  0. ]
 [ 0.  -2.   1.   1. ]]
[01-28 00:08:18][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  1.  1. ]]
[01-28 00:08:18][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]
[01-28 00:08:18][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]
[01-28 00:08:18][INFO] Sustitución hacia adelante
[01-28 00:08:18][INFO] y = 
[[ 3. ]
 [ 3. ]
 [-0.6]
 [ 3. ]]
[01-28 00:08:18][INFO] Sustitución hacia atrás
[01-28 00:08:18][INFO] i = 2
[01-28 00:08:18][INFO] suma = [0.]
[01-28 00:08:18][INFO] U[i, i] = 0.5
[01-28 00:08:18][INFO] y[i] = [-0.6]
[01-28 00:08:18][INFO] i = 1
[01-28 00:08:18][INFO] suma = [0.]
[01-28 00:08:18][INFO] U[i, i] = 1.5
[01-28 00:08:18][INFO] y[i] = [3.]
[01-28 00:08:18][INFO] i = 0
[01-28 00:08:18][INFO] suma = [0.]
[01-28 00:08:18][INFO] U[i, i] = 2.0
[01-28 00:08:18][INFO] y[i] = [3.]
Matriz L:
[[

\begin{cases}
2.1756x_1 + 4.0231x_2 - 2.1732x_3 + 5.1967x_4 = 17.102 \\
-4.0231x_1 + 6.0000x_2 + 1.1973x_4 = -6.1593 \\
-1.0000x_1 - 5.2107x_2 + 1.1111x_3 = 3.0004 \\
6.0235x_1 + 7.0000x_2 - 4.1561x_4 = 0.0000
\end{cases}

In [15]:
D = np.array([[2.1756, 4.0231, -2.1732, 5.1967],
              [
              -4.0231, 6.0000, 0, 1.973],
              [-1.0000, -5.2107, 1.1111, 0],
              [6.0235, 7.0000, 0, -4.1561]])

L1, U1 = descomposicion_LU(np.array(D))
b4 = np.array([17.102, -6.1593, 3.0004, 0.0000])
x_4 = resolver_LU(L1, U1, b4)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)   
print("Solución del sistema Ax=b:")
print(x_4)

[01-28 00:09:13][INFO] 
[[  2.1756       4.0231      -2.1732       5.1967    ]
 [  0.          13.43948042  -4.01866194  11.58269101]
 [  0.          -3.36150897   0.11220314   2.38862842]
 [  0.          -4.13860216   6.01685521 -18.54400331]]
[01-28 00:09:13][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.15826910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.28571362e+00]
 [ 0.00000000e+00  0.00000000e+00  4.77933394e+00 -1.49771876e+01]]
[01-28 00:09:13][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.15826910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.28571362e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.33134477e+01]]
[01-28 00:09:13][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.15826910e+01]
 [ 0.000000