# Métodos Númericos
## Isaac Gonález
### Tarea 10

---

1. Realice las siguientes multiplicaciones matriz-matriz

In [17]:
import numpy as np
def multiplicar_matrices(A, B):
    ''''
    Multiplica dos matrices A(m x n) y B(n x p) usando listas anidadas,
    retorna la matriz resultante (m x p)
    '''
    if not A or not B or not A[0] or not B[0]:
        raise ValueError("Las matrices no pueden estar vacías,")
    
    m, n = len(A), len(A[0])
    n2, p = len(B), len(B[0])
    
    #Verificar dimensiones compatibles
    if n != n2:
        raise ValueError(f"Dimensiones incompatibles: A es {m}x{n} y B es {n2}x{p}")

    #Multiplicación
    
    R = [[0 for _ in range(p)] for _ in range(m)]
    for i in range(m):
        for k in range(n):
            aik = A[i][k]
            for j in range(p):
                R[i][j] += aik * B[k][j]
    return np.array(R)


a.  

A = 
\begin{bmatrix}
2 & -3\\
3 & -1
\end{bmatrix} \\

B = 
\begin{bmatrix}
1 & 5\\
2 & 0
\end{bmatrix}




In [18]:
A = [
    [2,-3],
    [3,-1]
]

B = [
    [1,5],
    [2,0]
]

print(multiplicar_matrices(A,B))

[[-4 10]
 [ 1 15]]


Comprobación

In [8]:
import numpy as np

R = np.matmul(A,B)
print(R)


[[-4 10]
 [ 1 15]]


A = 

\begin{bmatrix}
2 & -3\\
3 & -1
\end{bmatrix}

B =

\begin{bmatrix}
1 & 5 & -4\\
-3 & 2 & 0
\end{bmatrix}


In [19]:
A = [
    [2,-3],
    [3,-1]
]

B = [
    [1, 5, -4],
    [-3, 2, 0]
]

print(multiplicar_matrices(A, B))

[[ 11   4  -8]
 [  6  13 -12]]


Comprobación

In [10]:
import numpy as np

R = np.matmul(A, B)
print(R)

[[ 11   4  -8]
 [  6  13 -12]]


c.

A =

\begin{bmatrix}
2 & -3 & 1\\
4 & 3 & 0\\
5 & 2 & -4
\end{bmatrix}

B=

\begin{bmatrix}
0 & 1 & -2\\
1 & 0 & -1\\
2 & 3 & -2
\end{bmatrix}

In [20]:
A = [
    [2,-3,1],
    [4,3,0],
    [5,2,-4]
]

B = [
    [0,1,-2],
    [1,0,-1],
    [2,3,-2]
]

print(multiplicar_matrices(A,B))

[[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]


Comprobación

In [14]:
import numpy as np

R = np.matmul(A,B)
print(R)

[[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]


d.  

A = 

\begin{bmatrix}
2 & 1 & 2\\
-2 & 3 & 0\\
2 & -1 & 3
\end{bmatrix}

B =

\begin{bmatrix}
1 & -2\\
-4 & 1\\
0 & 2
\end{bmatrix}

In [21]:
A = [
    [2,1,2],
    [-2,3,0],
    [2,-1,3]
]

B = [
    [1,-2],
    [-4,1],
    [0,2]
]

print(multiplicar_matrices(A,B))

[[ -2   1]
 [-14   7]
 [  6   1]]


comprobación

In [16]:
import numpy as np

R = np.matmul(A,B)
print(R)

[[ -2   1]
 [-14   7]
 [  6   1]]
