# Métodos Númericos
## Isaac González
### Tarea 11

---

In [2]:
%load_ext autoreload
%autoreload 2
from src import eliminacion_gaussiana, gauss_jacobi, gauss_seidel
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


1. Encuentre las primeras dos iteraciones del método de Jacobi para los siguientes sistemas lineales, por
medio de $𝐱^{(𝟎)} = 0:$

a.

\begin{cases}
3x_1 - x_2 + x_3 = 1 \\
3x_1 + 6x_2 + 2x_3 = 0 \\
3x_1 + 3x_2 + 7x_3 = 4
\end{cases}

In [7]:

A_1 = np.array([[3, 1, 1], [3, 6, 2], [3, 3, 7]], dtype=float)
b_1 = np.array([[1], [0], [4]], dtype=float)

sol  = gauss_jacobi(A = A_1, b = b_1, x = np.zeros_like(b_1), tol=1e-10, max_iter=2)


[01-28 00:38:15][INFO][hp] i= 0 x: [[0. 0. 0.]]
[01-28 00:38:16][INFO][hp] i= 2 x: [[ 0.14285714 -0.35714286  0.42857143]]


\begin{cases}
10x_1 - x_2 = 9 \\
- x_1 + 10x_2 - 2x_3 = 7 \\
-2x_2 + 10x_3 = 6
\end{cases}

In [8]:
A_2 = np.array([[10, -1, 0], [-1, 10, -2], [0, -2, 10]], dtype=float)
b_2 = np.array([[9], [7], [6]], dtype=float)

sol  = gauss_jacobi(A = A_2, b = b_2, x = np.zeros_like(b_2), tol=1e-10, max_iter=2)


[01-28 00:38:49][INFO][hp] i= 0 x: [[0. 0. 0.]]
[01-28 00:38:49][INFO][hp] i= 2 x: [[0.97 0.91 0.74]]


\begin{cases}
10x_1 + 5x_2 = 6 \\
5x_1 + 10x_2 - 4x_3 = 25 \\
-4x_2 + 8x_3 - x_4 = -11 \\
- x_3 + 5x_4 = -11
\end{cases}

In [9]:
A_3 = np.array([[10, 5, 0, 0], [5, 10, -4, 0], [0, -4, 8, -1], [0, 0, -1, 5]], dtype=float)
b_3 = np.array([[6], [25], [-11], [-11]], dtype=float)

sol  = gauss_jacobi(A = A_3, b = b_3, x = np.zeros_like(b_3), tol=1e-10, max_iter=2)


[01-28 00:39:14][INFO][hp] i= 0 x: [[0. 0. 0. 0.]]
[01-28 00:39:14][INFO][hp] i= 2 x: [[-0.65   1.65  -0.4   -2.475]]


\begin{cases}
4x_1 + x_2 + x_3 + x_5 = 6 \\
- x_1 - 3x_2 + x_3 + x_4 = 6 \\
2x_1 + x_2 + 5x_3 - x_4 - x_5 = 6 \\
- x_1 - x_2 - x_3 + 4x_4 = 6 \\
2x_2 - x_3 + x_4 + 4x_5 = 6
\end{cases}

In [10]:
A_4 = np.array([[4,1,1,0,0],
               [-1,-3,1,1,0],
               [2,1,5,-1,-1],
               [-1,-1,-1,4,0],
               [0, 2, -1, 1, 4]], dtype=float)
b_4 = np.array([[6], [6], [6], [6], [6]], dtype=float)

sol  = gauss_jacobi(A = A_4, b = b_4, x = np.zeros_like(b_4), tol=1e-10, max_iter=2)


[01-28 00:39:38][INFO][hp] i= 0 x: [[0. 0. 0. 0. 0.]]
[01-28 00:39:38][INFO][hp] i= 2 x: [[ 1.7   -1.6    1.6    1.675  2.425]]


2. Repita el ejercicio 1 usando el método de Gauss-Siedel.

In [ ]:
#a
gauss_seidel(A = A_1, b = b_1, x = np.zeros_like(b_1), tol=1e-10, max_iter=2)


[01-28 00:39:55][INFO][hp] i= 0 x: [[0. 0. 0.]]
[01-28 00:39:55][INFO][hp] i= 1 x: [[ 0.33333333 -0.16666667  0.5       ]]
[01-28 00:39:55][INFO][hp] i= 2 x: [[ 0.22222222 -0.27777778  0.5952381 ]]


array([[ 0.22222222],
       [-0.27777778],
       [ 0.5952381 ]])

In [12]:
#b
gauss_seidel(A = A_2, b = b_2, x = np.zeros_like(b_2), tol=1e-10, max_iter=2)


[01-28 00:40:35][INFO][hp] i= 0 x: [[0. 0. 0.]]
[01-28 00:40:35][INFO][hp] i= 1 x: [[0.9   0.79  0.758]]
[01-28 00:40:35][INFO][hp] i= 2 x: [[0.979  0.9495 0.7899]]


array([[0.979 ],
       [0.9495],
       [0.7899]])

In [13]:
#c

gauss_seidel(A = A_3, b = b_3, x = np.zeros_like(b_3), tol=1e-10, max_iter=2)


[01-28 00:40:55][INFO][hp] i= 0 x: [[0. 0. 0. 0.]]
[01-28 00:40:55][INFO][hp] i= 1 x: [[ 0.6    2.2   -0.275 -2.255]]
[01-28 00:40:55][INFO][hp] i= 2 x: [[-0.5       2.64     -0.336875 -2.267375]]


array([[-0.5     ],
       [ 2.64    ],
       [-0.336875],
       [-2.267375]])

In [14]:
#d

gauss_seidel(A = A_4, b = b_4, x = np.zeros_like(b_4), tol=1e-10, max_iter=2)


[01-28 00:41:15][INFO][hp] i= 0 x: [[0. 0. 0. 0. 0.]]
[01-28 00:41:15][INFO][hp] i= 1 x: [[ 1.5     -2.5      1.1      1.525    2.64375]]
[01-28 00:41:15][INFO][hp] i= 2 x: [[ 1.85       -1.74166667  1.64208333  1.93760417  2.29695312]]


array([[ 1.85      ],
       [-1.74166667],
       [ 1.64208333],
       [ 1.93760417],
       [ 2.29695312]])

3. Utilice el método de Jacobi para resolver los sistemas lineales en el ejercicio 1, con TOL = 10-3.

In [15]:
#a

gauss_jacobi(A = A_1, b = b_1, x = np.zeros_like(b_1), tol=1e-3, max_iter=2)


[01-28 00:41:47][INFO][hp] i= 0 x: [[0. 0. 0.]]
[01-28 00:41:47][INFO][hp] i= 2 x: [[ 0.14285714 -0.35714286  0.42857143]]


array([[ 0.14285714],
       [-0.35714286],
       [ 0.42857143]])

In [16]:
#b

gauss_jacobi(A = A_2, b = b_2, x = np.zeros_like(b_2), tol=1e-3, max_iter=2)


[01-28 00:42:08][INFO][hp] i= 0 x: [[0. 0. 0.]]
[01-28 00:42:08][INFO][hp] i= 2 x: [[0.97 0.91 0.74]]


array([[0.97],
       [0.91],
       [0.74]])

In [17]:
#c

gauss_jacobi(A = A_3, b = b_3, x = np.zeros_like(b_3), tol=1e-3, max_iter=2)


[01-28 00:42:29][INFO][hp] i= 0 x: [[0. 0. 0. 0.]]
[01-28 00:42:29][INFO][hp] i= 2 x: [[-0.65   1.65  -0.4   -2.475]]


array([[-0.65 ],
       [ 1.65 ],
       [-0.4  ],
       [-2.475]])

In [18]:
#d

gauss_jacobi(A = A_4, b = b_4, x = np.zeros_like(b_4), tol=1e-3, max_iter=2)


[01-28 00:42:51][INFO][hp] i= 0 x: [[0. 0. 0. 0. 0.]]
[01-28 00:42:51][INFO][hp] i= 2 x: [[ 1.7   -1.6    1.6    1.675  2.425]]


array([[ 1.7  ],
       [-1.6  ],
       [ 1.6  ],
       [ 1.675],
       [ 2.425]])

4. Utilice el método de Gauss-Siedel para resolver los sistemas lineales en el ejercicio 1, con TOL = 10-3.

In [19]:
#a
gauss_seidel(A = A_1, b = b_1, x = np.zeros_like(b_1), tol=1e-3, max_iter=2)


[01-28 00:43:59][INFO][hp] i= 0 x: [[0. 0. 0.]]
[01-28 00:43:59][INFO][hp] i= 1 x: [[ 0.33333333 -0.16666667  0.5       ]]
[01-28 00:43:59][INFO][hp] i= 2 x: [[ 0.22222222 -0.27777778  0.5952381 ]]


array([[ 0.22222222],
       [-0.27777778],
       [ 0.5952381 ]])

In [20]:
#b
gauss_seidel(A = A_2, b = b_2, x = np.zeros_like(b_2), tol=1e-3, max_iter=2)


[01-28 00:44:19][INFO][hp] i= 0 x: [[0. 0. 0.]]
[01-28 00:44:19][INFO][hp] i= 1 x: [[0.9   0.79  0.758]]
[01-28 00:44:19][INFO][hp] i= 2 x: [[0.979  0.9495 0.7899]]


array([[0.979 ],
       [0.9495],
       [0.7899]])

In [21]:
#c
gauss_seidel(A = A_3, b = b_3, x = np.zeros_like(b_3), tol=1e-3, max_iter=2)


[01-28 00:44:37][INFO][hp] i= 0 x: [[0. 0. 0. 0.]]
[01-28 00:44:37][INFO][hp] i= 1 x: [[ 0.6    2.2   -0.275 -2.255]]
[01-28 00:44:37][INFO][hp] i= 2 x: [[-0.5       2.64     -0.336875 -2.267375]]


array([[-0.5     ],
       [ 2.64    ],
       [-0.336875],
       [-2.267375]])

In [22]:
#d
gauss_seidel(A = A_4, b = b_4, x = np.zeros_like(b_4), tol=1e-3, max_iter=2)


[01-28 00:45:00][INFO][hp] i= 0 x: [[0. 0. 0. 0. 0.]]
[01-28 00:45:00][INFO][hp] i= 1 x: [[ 1.5     -2.5      1.1      1.525    2.64375]]
[01-28 00:45:00][INFO][hp] i= 2 x: [[ 1.85       -1.74166667  1.64208333  1.93760417  2.29695312]]


array([[ 1.85      ],
       [-1.74166667],
       [ 1.64208333],
       [ 1.93760417],
       [ 2.29695312]])

5. El sistema lineal

\begin{cases}
2x_1 - x_2 + x_3 = -1 \\
2x_1 + 2x_2 + 2x_3 = 4 \\
- x_1 - x_2 + 2x_3 = -5
\end{cases}

tiene la solución $(1, 2, -1)^t$

a) Muestre que el método de Jacobi con $x(0) = 0 $ falla al proporcionar una buena aproximación
después de 25 iteraciones

In [23]:
A = np.array([[2, -1, 1], [2, 2, 2], [-1, -1, 2]], dtype=float)
b = np.array([[-1],  [4], [-5]], dtype=float)

gauss_jacobi(A = A, b = b, x = np.zeros_like(b), tol=1e-10, max_iter=25)


[01-28 00:47:26][INFO][hp] i= 0 x: [[0. 0. 0.]]
[01-28 00:47:26][INFO][hp] i= 25 x: [[-20.82787284   2.         -22.82787284]]


array([[-20.82787284],
       [  2.        ],
       [-22.82787284]])

b) Utilice el método de Gauss-Siedel con $x(0) = 0: $ para aproximar la solución para el sistema lineal
dentro de $10^{−5}$

In [24]:
gauss_seidel(A = A, b = b, x = np.zeros_like(b), tol=1e-5, max_iter=25)


[01-28 00:48:04][INFO][hp] i= 0 x: [[0. 0. 0.]]
[01-28 00:48:04][INFO][hp] i= 1 x: [[-0.5  2.5 -1.5]]
[01-28 00:48:04][INFO][hp] i= 2 x: [[ 1.5   2.   -0.75]]
[01-28 00:48:04][INFO][hp] i= 3 x: [[ 0.875  1.875 -1.125]]
[01-28 00:48:04][INFO][hp] i= 4 x: [[ 1.      2.125  -0.9375]]
[01-28 00:48:04][INFO][hp] i= 5 x: [[ 1.03125  1.90625 -1.03125]]
[01-28 00:48:04][INFO][hp] i= 6 x: [[ 0.96875   2.0625   -0.984375]]
[01-28 00:48:04][INFO][hp] i= 7 x: [[ 1.0234375  1.9609375 -1.0078125]]
[01-28 00:48:04][INFO][hp] i= 8 x: [[ 0.984375    2.0234375  -0.99609375]]
[01-28 00:48:04][INFO][hp] i= 9 x: [[ 1.00976562  1.98632812 -1.00195312]]
[01-28 00:48:04][INFO][hp] i= 10 x: [[ 0.99414062  2.0078125  -0.99902344]]
[01-28 00:48:04][INFO][hp] i= 11 x: [[ 1.00341797  1.99560547 -1.00048828]]
[01-28 00:48:04][INFO][hp] i= 12 x: [[ 0.99804688  2.00244141 -0.99975586]]
[01-28 00:48:04][INFO][hp] i= 13 x: [[ 1.00109863  1.99865723 -1.00012207]]
[01-28 00:48:04][INFO][hp] i= 14 x: [[ 0.99938965  2.0007

array([[ 1.00000226],
       [ 1.9999975 ],
       [-1.00000012]])

6. El sistema lineal

\begin{cases}
x_1 - x_3 = 0.2 \\
-\frac{1}{2}x_1 + x_2 - \frac{1}{4}x_3 = -1.425 \\
x_1 - \frac{1}{2}x_2 + x_3 = 2
\end{cases}

tiene la solución $(0.9, -0.8, 0.7)^t$

a) ¿La matriz de coeficientes

A =
\begin{bmatrix}
1 & 0 & -1 \\
-\frac{1}{2} & 1 & -\frac{1}{4} \\
1 & -\frac{1}{2} & 1
\end{bmatrix}

tiene diagonal estrictamente dominante?

La matriz no cumple la condición de dominancia estricta, ya que esta propiedad no se verifica en todas sus filas; en particular, se incumple en la primera y en la tercera fila.

b) Utilice el método iterativo de Gauss-Siedel para aproximar la solución para el sistema lineal con
una tolerancia de $10_{22}$ y un máximo de 300 iteraciones.

In [25]:
A = np.array([[1, 0, -1], [-1/2, 1, -1/4], [1, -1/2, 1]], dtype=float)
b = np.array([[0.2], [-1.425], [2]], dtype=float)

gauss_seidel(A = A, b = b, x = np.zeros_like(b), tol=1e-22, max_iter=300)


[01-28 00:51:52][INFO][hp] i= 0 x: [[0. 0. 0.]]
[01-28 00:51:52][INFO][hp] i= 1 x: [[ 0.2    -1.325   1.1375]]
[01-28 00:51:52][INFO][hp] i= 2 x: [[ 1.3375    -0.471875   0.4265625]]
[01-28 00:51:52][INFO][hp] i= 3 x: [[ 0.6265625  -1.00507812  0.87089844]]
[01-28 00:51:52][INFO][hp] i= 4 x: [[ 1.07089844 -0.67182617  0.59318848]]
[01-28 00:51:52][INFO][hp] i= 5 x: [[ 0.79318848 -0.88010864  0.7667572 ]]
[01-28 00:51:52][INFO][hp] i= 6 x: [[ 0.9667572  -0.7499321   0.65827675]]
[01-28 00:51:52][INFO][hp] i= 7 x: [[ 0.85827675 -0.83129244  0.72607703]]
[01-28 00:51:52][INFO][hp] i= 8 x: [[ 0.92607703 -0.78044223  0.68370185]]
[01-28 00:51:52][INFO][hp] i= 9 x: [[ 0.88370185 -0.81222361  0.71018634]]
[01-28 00:51:52][INFO][hp] i= 10 x: [[ 0.91018634 -0.79236024  0.69363354]]
[01-28 00:51:52][INFO][hp] i= 11 x: [[ 0.89363354 -0.80477485  0.70397904]]
[01-28 00:51:52][INFO][hp] i= 12 x: [[ 0.90397904 -0.79701572  0.6975131 ]]
[01-28 00:51:52][INFO][hp] i= 13 x: [[ 0.8975131  -0.80186517  0

array([[ 0.9],
       [-0.8],
       [ 0.7]])

c) . ¿Qué pasa en la parte b) cuando el sistema cambia por el siguiente?

\begin{cases}
x_1 - 2x_3 = 0.2 \\
-\frac{1}{2}x_1 + x_2 - \frac{1}{4}x_3 = -1.425 \\
x_1 - \frac{1}{2}x_2 + x_3 = 2
\end{cases}

In [26]:
B = np.array([[1, 0, -2], 
              [-1/2, 1, -1/4], 
              [1, -1/2, 1]], dtype=float)

gauss_seidel(A = B, b = b, x = np.zeros_like(b), tol=1e-10, max_iter=25)


[01-28 00:53:50][INFO][hp] i= 0 x: [[0. 0. 0.]]
[01-28 00:53:50][INFO][hp] i= 1 x: [[ 0.2    -1.325   1.1375]]
[01-28 00:53:50][INFO][hp] i= 2 x: [[ 2.475      0.096875  -0.4265625]]
[01-28 00:53:50][INFO][hp] i= 3 x: [[-0.653125   -1.85820313  1.72402344]]
[01-28 00:53:50][INFO][hp] i= 4 x: [[ 3.64804688  0.8300293  -1.23303223]]
[01-28 00:53:50][INFO][hp] i= 5 x: [[-2.26606445 -2.86629028  2.83291931]]
[01-28 00:53:50][INFO][hp] i= 6 x: [[ 5.86583862  2.21614914 -2.75776405]]
[01-28 00:53:50][INFO][hp] i= 7 x: [[-5.31552811 -4.77220507  4.92942557]]
[01-28 00:53:50][INFO][hp] i= 8 x: [[10.05885115  4.83678197 -5.64046016]]
[01-28 00:53:50][INFO][hp] i= 9 x: [[-11.08092033  -8.3755752    8.89313272]]
[01-28 00:53:50][INFO][hp] i= 10 x: [[ 17.98626545   9.79141591 -11.0905575 ]]
[01-28 00:53:50][INFO][hp] i= 11 x: [[-21.98111499 -15.18819687  16.38701656]]
[01-28 00:53:50][INFO][hp] i= 12 x: [[ 32.97403311  19.1587707  -21.39464777]]
[01-28 00:53:50][INFO][hp] i= 13 x: [[-42.58929553 -

array([[-1996.78257085],
       [-1249.43910678],
       [ 1374.06301746]])

Lo que sucede esque el sistema diverge y cambia totalmente en la respuesta

7. Repita el ejercicio 11 usando el método de Jacobi.

In [27]:
#b

gauss_jacobi(A = A, b = b, x = np.zeros_like(b), tol=1e-22, max_iter=300)


[01-28 00:55:22][INFO][hp] i= 0 x: [[0. 0. 0.]]
[01-28 00:55:22][INFO][hp] i= 300 x: [[ 0.90025541 -0.80004033  0.70012933]]


array([[ 0.90025541],
       [-0.80004033],
       [ 0.70012933]])

In [28]:
#c

gauss_jacobi(A=B, b=b, x = np.zeros_like(b), tol=1e-22, max_iter=300)


[01-28 00:55:37][INFO][hp] i= 0 x: [[0. 0. 0.]]
[01-28 00:55:37][INFO][hp] i= 300 x: [[ 1.34478913e+43 -7.28028158e+42  1.56650340e+43]]


array([[ 1.34478913e+43],
       [-7.28028158e+42],
       [ 1.56650340e+43]])

8. Un cable coaxial está formado por un conductor interno de 0.1 pulgadas cuadradas y un conductor externo
de 0.5 pulgadas cuadradas. El potencial en un punto en la sección transversal del cable se describe
mediante la ecuación de Laplace.
Suponga que el conductor interno se mantiene en 0 volts y el conductor externo se mantiene en 110 volts. Aproximar
el potencial entre los dos conductores requiere resolver el siguiente sistema lineal.

\begin{bmatrix}
4 & -1 & 0 & 0 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
-1 & 4 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & -1 & 4 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & -1 & 4 & 0 & -1 & 0 & 0 & 0 & 0 & 0 & 0 \\
-1 & 0 & 0 & 0 & 4 & 0 & -1 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & -1 & 0 & 4 & 0 & -1 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & -1 & 0 & 4 & 0 & -1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & -1 & 0 & 4 & 0 & 0 & 0 & -1 \\
0 & 0 & 0 & 0 & 0 & 0 & -1 & 0 & 4 & -1 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 4 & -1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 4 & -1 \\
0 & 0 & 0 & 0 & 0 & -1 & 0 & 0 & 0 & 0 & -1 & 4
\end{bmatrix}

\begin{bmatrix}
w_1 \\ w_2 \\ w_3 \\ w_4 \\ w_5 \\ w_6 \\
w_7 \\ w_8 \\ w_9 \\ w_{10} \\ w_{11} \\ w_{12}
\end{bmatrix}

=

\begin{bmatrix}
220 \\ 110 \\ 110 \\ 220 \\ 110 \\ 110 \\
110 \\ 110 \\ 220 \\ 110 \\ 110 \\ 220
\end{bmatrix}

a. ¿La matriz es estrictamente diagonalmente dominante?

Sí. La matriz es estrictamente diagonalmente dominante por filas.


$|a_{ii}| > \sum_{j \ne i} |a_{ij}|$


En este caso, para todas las filas se tiene:


$|a_{ii}| = 4$


y la suma de los valores absolutos de los elementos fuera de la diagonal es:


$\sum_{j \ne i} |a_{ij}| = 1 + 1 = 2$


Como se cumple que


$4 > 2$


en todas las filas, se concluye que la matriz es estrictamente diagonalmente dominante.

b. Resuelva el sistema lineal usando el método de Jacobi con x(0) = 0 y TOL = 10-2.

In [29]:
A = np.array([
    [ 4, -1,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0],
    [-1,  4, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [ 0, -1,  4, -1,  0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0, -1,  4,  0, -1,  0,  0,  0,  0,  0,  0],
    [-1,  0,  0,  0,  4, -1,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0, -1,  0,  4,  0, -1,  0,  0,  0,  0],
    [ 0,  0,  0,  0, -1,  0,  4,  0, -1,  0,  0,  0],
    [ 0,  0,  0,  0,  0, -1,  0,  4,  0,  0,  0, -1],
    [ 0,  0,  0,  0,  0,  0, -1,  0,  4, -1,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0, -1,  4, -1,  0],
    [ 0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  4, -1],
    [ 0,  0,  0,  0,  0, -1,  0,  0,  0,  0, -1,  4]
], dtype=float)

b = np.array([[220], [110], [110], [220], [110], [110], [110], [110], [220], [110], [110], [220]], dtype=float)

gauss_jacobi(A=A, b=b, x = np.zeros_like(b), tol=1e-2, max_iter=30)


[01-28 01:01:23][INFO][hp] i= 0 x: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


array([[87.99776206],
       [65.99776204],
       [65.99776204],
       [87.99776206],
       [65.99776204],
       [65.99776204],
       [65.99776204],
       [65.99776204],
       [87.99776206],
       [65.99776204],
       [65.99776204],
       [87.99776206]])

c. Repita la parte b) mediante el método de Gauss-Siedel.

In [30]:
gauss_seidel(A=A, b=b, x = np.zeros_like(b), tol=1e-2, max_iter=30)


[01-28 01:01:51][INFO][hp] i= 0 x: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[01-28 01:01:51][INFO][hp] i= 1 x: [[55.         41.25       37.8125     64.453125   41.25       43.61328125
  37.8125     38.40332031 64.453125   43.61328125 38.40332031 75.50415039]]
[01-28 01:01:51][INFO][hp] i= 2 x: [[75.625      55.859375   57.578125   80.29785156 57.30957031 57.17529297
  57.94067383 60.66986084 80.38848877 57.19795227 60.67552567 84.46270466]]
[01-28 01:01:51][INFO][hp] i= 3 x: [[83.29223633 62.71759033 63.25386047 85.10728836 62.61688232 63.9442873
  63.25134277 64.60174799 85.11232376 63.94696236 64.60241675 87.13667601]]
[01-28 01:01:51][INFO][hp] i= 4 x: [[86.33361816 64.89686966 65.00103951 87.2363317  65.06947637 65.45951992
  65.04545003 65.64904898 87.2481031  65.46262996 65.64982649 87.7773366 ]]
[01-28 01:01:51][INFO][hp] i= 5 x: [[87.49158651 65.6231565  65.71487205 87.79359799 65.73777661 65.86066174
  65.74646993 65.90949959 87.80227497 65.86302537 65.91009049 87.94268806]]
[

array([[87.99903836],
       [65.99937543],
       [65.99959325],
       [87.99973663],
       [65.9995979 ],
       [65.99983076],
       [65.99967395],
       [65.99989192],
       [87.99976476],
       [65.99983978],
       [65.99989417],
       [87.99993123]])